### ISSUE TITLE
Works in Editor, Not in Export

### ISSUE THREAD

**Issue by lunarcloud** [ephread/inkgd#10]
**Describe the bug**
ERROR: get_node: Node not found: __InkRuntime
   At: scene/main/node.cpp:1382.

**To Reproduce**
Export this project: https://github.com/lunarcloud/not-a-halloween-game/tree/inkgd

**Expected behavior**
To behave the same in export as editor - no find and use the static runtime node

**Ink files**
See "to reproduce"

**Environment:**
 - OS: Kubuntu 19.04
 - Inklecate version:(precompiled main.json)
 - _inkgd_ version: ca863520ea5b3b13fd9c4872014b77c91cfa907b
- Godot: 3.1.1 (Standard Version)

**Additional context**
I tested the linux and web exports on my machine.

**Comment by ephread** [comment]
Ouch @lunarcloud, that's definitely a big problem, thanks for opening the issue! I'll have a look this weekend.

**Comment by ephread** [comment]
I couldn't reproduce the issue with you project, but I managed to trigger it with the example project. The good news is that PR #9 should fix the issue. It was merged a few days ago, so can you give it a try with `master/HEAD`? If that works, I'll create a new release.

**Comment by lunarcloud** [comment]
Yes, that fixed it for me 
(verified after *also* wrestling with godot about including the json file in the export)

**Comment by ephread** [comment]
Awesome, I'll make a new release as soon as possible!
