### ISSUE TITLE
Best way to integrate Mono?

### ISSUE THREAD

**Issue by shrnjad** [ephread/inkgd#14]
Thank you very much for providing this!

What is the best way to integrate Mono? I saw in the doku that one should link to the mono runtime. But is there a preferred way to use Mono? Like using the Godot Mono version? Or better to use Godot without Mono but have a separate installation of Mono?

Maybe it would also be interesting to add to the readme.

Thank you! :)

**Comment by 2shady4u** [comment]
There's a C# implementation for Ink in Godot also floating around. Maybe it is better to use that one if you are going to use Mono anyway?

**Comment by shrnjad** [comment]
Right now I am on Godot-Mono and gotot-ink, because I had not found your plugin when researching.

Basically, I am still at the beginning of the project and I would like to switch to your plugin to avoid Godot-Mono (I do not intend to use C# otherwise)

So I guess you answer is to Use Godot without mono and have a separate installation of mono for the inkgd plugin?

**Comment by 2shady4u** [comment]
mmmh this is not my plugin 🤣 

So:
- godot-ink (https://github.com/paulloz/godot-ink ) works well with Godot Mono
- gdink (https://github.com/ephread/inkgd) works well with Godot GDscript

Are you using Godot Mono (C#)?
Yes? Then use godot-ink
No? Then use gdink

**Comment by ephread** [comment]
@shrnjad as @2shady4u perfectly summarised, _inkgd_ has no dependencies on mono, it’s implementation of the runtime in pure GDScript. If you intend to you use this plugin, you can use the vanilla version of Godot.

**Comment by shrnjad** [comment]
Thank you for the answer. I am using now the Godot version without Mono, which I prefer.

However, in the configuration for inkgd, there is still the field called 'Mono', where I put the pointer to my Mono installation. What is that used for? Will my team-members be able to run the project on their machines without having to install Mono?

**Comment by ephread** [comment]
> However, in the configuration for inkgd, there is still the field called 'Mono', where I put the pointer to my Mono installation. What is that used for?

It’s only required if you want to have the Godot editor recompile (through _inklecate_) your master `*.ink` file every time you build/preview your project. [See here].(https://github.com/ephread/inkgd#editor)

> Will my team-members be able to run the project on their machines without having to install Mono?

The editor plugin is completely optional and not required to embed the runtime. Plus, if the path to either _inklecate_ or _mono_ is not provided (or can’t be resolved), then the file will no be compiled. The build should go through either way.

**Comment by shrnjad** [comment]
Thank you Frédéric! 🙏
