### ISSUE TITLE
Compiling the example doesn't work)

### ISSUE THREAD

**Issue by RobertWalter83** [ephread/inkgd#2]
**Describe the bug**
I cloned the current master branch and wanted to use the editor to compile "the_intercept" example.
I tried setting the path to the executable both via absolute path as well as using a resource-path (res://).
In case of an absolute path, pressing "Compile" gives me this output:
![image](https://user-images.githubusercontent.com/5462981/58162493-917d2000-7c82-11e9-907e-351f05c7d9cb.png)

In case of a resource-path, I get no output at all.

**To Reproduce**
I cloned the master branch and downloaded the latest inklecate. This does not allow me to compile with the plugin. Not sure what I'm missing.

**Expected behavior**
The ink file to be compiled.

**Ink files**
It's the example that comes with this repository.

**Environment:**
 - OS: Windows 10
 - Inklecate version: 0.8.2
 - _inkgd_ version: 0.1.1

**Comment by ephread** [comment]
First bug! Oh well, this project is off to a great start it seems.

Looks like I didn't test the editor plugin properly on Windows. I'm able to reproduce the issue, give me a few minutes, I should be able to fix the issue fairly quickly.

**Comment by RobertWalter83** [comment]
No worries, bugs are part of the equation.

**Comment by ephread** [comment]
Should be fixed in master. I forgot to add a chunk of code 😅, I also added in the README that paths to inklecate should be absolute for now.

I'm getting off Github, I hope you won't find any blocking issue until tomorrow!

**Comment by RobertWalter83** [comment]
It works for me now, thanks.
