### ISSUE TITLE
Best way to implement multiple ink stories?

### ISSUE THREAD

**Issue by mcoorlim** [ephread/inkgd#23]
Hi, I'm very new to gdscript, and I've been using your implementation of The Intercept as a guide to building my own ink runner node. I've got something working, I'm happy so far, inkgd has been a great help.

I'd like to link self-contained ink stories together into a sort-of anthology. How would I go about having the runner stop the current story and load a new .json? Or would it be easier/a better practice to instance a new ink runner node each time?

Thanks!

**Comment by ephread** [comment]
Hi @mcoorlim,

> I've got something working, I'm happy so far, inkgd has been a great help.

I glad it’s been useful!

> I'd like to link self-contained ink stories together into a sort-of anthology. How would I go about having the runner stop the current story and load a new .json? Or would it be easier/a better practice to instance a new ink runner node each time?

I think either way is fine, although keeping the same ink runner is probably easier. Assuming you don’t need to keep any references to the previous stories in the anthology, you can just replace the content of `story` with a new `Story`, clear the screen and call `continue()` to get the new content.

ink stories are idle until queried / continued so you can override them at any time.

**Comment by mcoorlim** [comment]
Works like a charm, thanks.
