### ISSUE TITLE
Bug - inkplayer not running with HTML export/Loads in Background turned off

### ISSUE THREAD

**Issue by GreenCloversGames** [ephread/inkgd#58]
**Describe the bug**
inkplayer create_story method throws "InkRuntime could not be found" error if run in HTML or "Loads In Background" turned off.

**To Reproduce**

1. Install inkgd plugin and create inkPlayer node and load with InkFile.
2. Turn "Loads in Background" off. 
3. In code, have the inkplayer run the "create_story" method and run the scene.

**Expected behavior**
Scene should run as normal, with no errors.

**Environment:**
 - OS: Windows
 - Godot version: 3.4.3 vanilla
 - _inkgd_ version: 0.4.5

**Comment by ephread** [comment]
Hey @GreenCloversGames, thanks for reporting and investigating this issue!
