### ISSUE TITLE
Can't download the example

### ISSUE THREAD

**Issue by zyq0825** [ephread/inkgd#7]
**Describe the bug**
Hello I don't know if it's only me but whether I install inkgd from assert lib or download here, I couldn't get the example folder... So I tried to download the tscn file directly but my godot said " Error while parsing" when I tried to open the scene file. 

**To Reproduce**
Clone or Download ->Download ZIP

**Expected behavior**
Be able to run the example

**Environment:**
 - Windows 10 x64
-  Godot 3.1

**Comment by zyq0825** [comment]
Used extension for chrome and got the example! 😂

**Comment by ephread** [comment]
To help anyone stumbling upon this issue, here's the problem and a potential solution.

inkgd has a `.gitattributes` file which makes sure that only `addons/inkgd` is added to Github archive. Removing unnecessary files is important to prevent clutter in your project (Godot fetches the archive directly from Github and copies it content into the project, which means you could end up with a bunch of files you don't want).

The only way to get the example folder (and a bunch of other important files) is to clone the project.
